### ISSUE TITLE
Additional molecule drivers?

### ISSUE THREAD

**Issue by gardar** [ansible/creator-ee#20]
Will additional molecule drivers (containers/podman/docker) and the required binaries (podman/docker) be added to this container?

Asking since the [toolset](https://github.com/ansible-community/toolset) container that this is superseding included it.

**Comment by madrover** [comment]
I agree with this; this is very handy to have in the toolset container. Otherwise we're forced to add an overlay on top of the vanilla container, which somewhat complicate things...

**Comment by ziegenberg** [comment]
I'm afraid, this issue is not fully solved yet. The docker/podman binaries are still missing... 🙈
