### ISSUE TITLE
UID: readonly variable

### ISSUE THREAD

**Issue by tomjones1977** [ansible/creator-ee#207]
I'm trying to use  the creator-ee image as part of VSCodium to do ansible-lint checks.

When running the latest version of the creator-ee image it crashes out on load with the following error:

```
docker run --rm --workdir /home/tom/work -v /home/tom/work:/home/tom/work -e ANSIBLE_FORCE_COLOR=0 --user=1000 --name ansible_language_server_5c91e33b-5ed8-46ff-ab8c-38e9c796d12e quay.io/ansible/creator-ee:latest whereis ansible-lint   
```

Error:
```
/usr/bin/entrypoint: line 43: UID: readonly variable
```

It appears that VSCodium is trying to set the UID to my actual account UID but the container fails to load.

I cannot find a setting to ignore the `--user` flag in VSCodium.  Is this a container issue or a VSC issue?

**Comment by ssbarnea** [comment]
At this moment we only test the container as being used by vscode-ansible extension and not as a dev-container as vscode advertises them. Still, we are likely that we will also cover this in the near future.

Still, your error message is clear enough to make a fix easy to implement.
