### ISSUE TITLE
Container is missing `which` - causing molecule test to break when using podman driver

### ISSUE THREAD

**Issue by RootPrivileges** [ansible/creator-ee#217]
I'm just moving some old ansible modules from ansible/toolset to ansible/creator-ee, using the Gitlab CI public runners and `docker:dind`, before updating the modules to support Ubuntu 22.04.

When switching out the old container for this new one, I get the following error; apparently the ansible podman driver [is trying to check for the location of the podman binary](https://gitlab.com/rootprivileges-ansible/public/ubuntu-vm/-/jobs/3266138178#L81) using `which` prior to running the playbook, but that binary is not installed within this container.

```
INFO     Running default > create
Molecule default > create
00:01
PLAY [Create] ******************************************************************
TASK [get podman executable path] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "which podman", "msg": "[Errno 2] No such file or directory: b'which'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

Running a `dnf install -y which` as [the first step of my build fixes the issue](https://gitlab.com/rootprivileges-ansible/public/ubuntu-vm/-/jobs/3266208053#L25).

**Comment by ssbarnea** [comment]
Which is missing by design, podman driver needs to be updated to avoid using which.
