### ISSUE TITLE
creator_ee still pulling molecule_podman 2.0.3 missing podman path lookup fix

### ISSUE THREAD

**Issue by jacobsin** [ansible/creator-ee#287]
a follow-up on https://github.com/ansible/creator-ee/issues/217

the fix seems to have been done by [molecule-podman PR #142](https://github.com/ansible-community/molecule-podman/pull/142) for [release v2.1.0](https://github.com/ansible-community/molecule-podman/releases/tag/v2.1.0)

but on [pypi](https://pypi.org/project/molecule-podman/) it is still show v2.0.3 before the fix
also [molecule-podman](https://github.com/ansible-community/molecule-podman) has been archived since 8 Jan 2023, so cannot raise issue there

how do we make podman driver working again?

**Comment by ssbarnea** [comment]
Molecule-podman is now part of https://github.com/ansible-community/molecule-plugins - We did not decided yet about inclusion of molecule-plugins on creator-ee, but we will make a decision in the next months. Meanwhile you will have to build you own container and add the newer version of the plugin.
