### ISSUE TITLE
which command is not found when run molecule command

### ISSUE THREAD

**Issue by miyuk** [ansible/creator-ee#314]
I use this container image for testing role.

When run `molecule test` command, I showed below error messages.

I guess `which` command is necessary command in this containers.
`which` can be installed by `microdnf install --assumeyes which` command.

## error message
```bash
PLAY [Create] ******************************************************************
TASK [get podman executable path] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "which podman", "msg": "[Errno 2] No such file
```
## 

## molecule.yml
```yaml
---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
```

**Comment by ssbarnea** [comment]
We will not install which, but we will upgrade molecule and podman plugin to use version that no longer needs it.
