### ISSUE TITLE
`creator-ee` is not built by ansible-builder

### ISSUE THREAD

**Issue by cidrblock** [ansible/creator-ee#330]
This allows for issues when using it to test other devtools that need to be compatible with builder version 3

Related: https://github.com/ansible/ansible-builder/issues/292

**Comment by ssbarnea** [comment]
It should be noted this bug is blocked by ansible-builder itself as we require to be able to build multi-architecture images (x86_64 and arm64), something that is not yet supported by builder.

**Comment by ssbarnea** [comment]
New container sorts this: https://github.com/ansible/ansible-dev-tools
