### ISSUE TITLE
Molecule tests failing with "One or more supplied key could not be found in the database" since v0.20.0

### ISSUE THREAD

**Issue by ng-bsy** [ansible/creator-ee#374]
# Problem
Molecule tests failing with following error since [v0.20.0](https://github.com/ansible/creator-ee/releases/tag/v0.20.0):
```
PLAY [Destroy] *****************************************************************
TASK [Get passwd entries for USER env] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "One or more supplied key could not be found in the database."}
```

# Analysis
Although there are no notable changes mentioned in the release notes of v0.20.0, I noticed, that molecule has been silently updated to a new major version (6.0.2) via https://github.com/ansible/creator-ee/commit/9c60055c278fe6ce4aa3086817e094a4e610901a and molecule-plugins to 23.5.0.

The only recent issue with molcule I could find relating to this is https://github.com/ansible-community/molecule-plugins/issues/181 whose supposed fix https://github.com/ansible-community/molecule-plugins/pull/182/commits/fc4359b0252ff7e9175805c06f8ce1dcd98558b7 (Nov 14th '23) hasn't been rolled out into the most recent release [v23.5.0](https://github.com/ansible-community/molecule-plugins/releases/tag/v23.5.0) (Aug 3rd '23)

# Proposed Solution/Workaround
Until mentioned fix is rolled out and the version of molecule-plugins updated, it should be pinned to an earlier version
I'll be pinning creator-ee to v0.19.0 until then

**Comment by evgeni** [comment]
Why me?
