### ISSUE TITLE
Molecule testing fails at async Docker container creation / deletion task

### ISSUE THREAD

**Issue by AnonJo** [ansible/creator-ee#59]
Hey there,

while trying this Docker image for Molecule testing I always get the following error:

```
TASK [Create molecule instance(s)] *********************************************
changed: [localhost] => (item=instance-ubuntu2004)

TASK [Wait for instance(s) creation to complete] *******************************
failed: [localhost] (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '658783536765.117', 'results_file': '/home/runner/.ansible_async/658783536765.117', 'changed': True, 'item': {'command': '', 'image': 'private.registry/de-docker-images/de-ansible-molecule/docker-ubuntu2004-ansible/docker-ubuntu2004-ansible:latest', 'name': 'instance-ubuntu2004', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'}) => {"ansible_job_id": "658783536765.117", "ansible_loop_var": "item", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "658783536765.117", "ansible_loop_var": "item", "changed": true, "failed": 0, "finished": 0, "item": {"command": "", "image": "private.registry/de-docker-images/de-ansible-molecule/docker-ubuntu2004-ansible/docker-ubuntu2004-ansible:latest", "name": "instance-ubuntu2004", "pre_build_image": true, "privileged": true, "volumes": ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]}, "results_file": "/home/runner/.ansible_async/658783536765.117", "started": 1}, "msg": "could not find job", "results_file": "/root/.ansible_async/658783536765.117", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

```
Or while destroying:

```
TASK [Destroy molecule instance(s)] ********************************************
changed: [localhost] => (item=instance-ubuntu2004)

TASK [Wait for instance(s) deletion to complete] *******************************
failed: [localhost] (item=instance-ubuntu2004) => {"ansible_job_id": "52085761132.204", "ansible_loop_var": "item", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "52085761132.204", "ansible_loop_var": "item", "changed": true, "failed": 0, "finished": 0, "item": {"command": "", "image": "private.registry/de-docker-images/de-ansible-molecule/docker-ubuntu2004-ansible/docker-ubuntu2004-ansible:latest", "name": "instance-ubuntu2004", "pre_build_image": true, "privileged": true, "volumes": ["/sys/fs/cgroup:/sys/fs/cgroup:ro"]}, "results_file": "/home/runner/.ansible_async/52085761132.204", "started": 1}, "msg": "could not find job", "results_file": "/root/.ansible_async/52085761132.204", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

The async files are there in the root folder, so I dont know what the problem is here.

Here is the Molecule config:

```
---
dependency:
  name: galaxy
driver:
  name: docker
    #lint: |
    #  set -e
    #  yamllint .
    #  ansible-lint
platforms:
  - name: instance-${MOLECULE_DISTRO:-ubuntu2004}
    image: "private.registry/de-docker-images/de-ansible-molecule/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  test_sequence:
    - dependency
    # - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
```

It seems this is an issue with the Python 3.8 version. When using another image with Python 3.10 and the same Molecule version it works flawlessly.

Kind regards,

AnonJo

**Comment by ssbarnea** [comment]
We removed any support for docker in last release https://github.com/ansible/creator-ee/releases/tag/v0.5.0

**Comment by Xiol** [comment]
Can I ask why this was removed?

Our CI/CD pipelines were using the toolset image until today, when that has been removed (I appreciate this has been deprecated for some time).

I'm trying to move them over to this creator-ee image, but without the docker driver I can't spawn the test containers.

**Comment by ssbarnea** [comment]
Temporary workaround: use older versions of creator-ee.

Long story: community.docker collection has a hard dependency on docker-compose python package which is EOL/unmaintained. That one has a pinned down hard-dependency on jsonschema python dependency. Ansible-lint requires a version that is newer than the maximal version supported by docker-compose.

If you want this module back you will have to pursuit an updated of either collection or the docker-compose, so they would no longer conflict.

Docker created a timebomb when they added all those pinnings to https://github.com/docker/compose/blob/master/setup.py (v1), and I am not sure if they are willing to backport a patch to unpin them. Please try it as that would be the easiest way to fix this problem.

The harder fix is to refactor the collection to remove the dependency on docker-compose python package and replace it with command line calls to compose, so it could use v2 (which is written in go).

**Comment by AnonJo** [comment]
I also get the above error with the older versions (tested quay.io/ansible/creator-ee:v0.4.2 and quay.io/ansible/creator-ee:v0.3.1.

Also it seems ansible/toolset is gone, so our complete testing framework isnt working anymore :(

**Comment by Xiol** [comment]
We have been successful with the v0.4.2 image but with quite a few hacky workarounds. We've had to build our own image `FROM` the v0.4.2 image with the following changes:

(entrypoint.sh can be retrieved from the diff link above the `ADD`)

```Dockerfile
# Use older version of creator-ee - this was the last version 
# that included the docker stuff.
# https://github.com/ansible/creator-ee/pull/65
FROM quay.io/ansible/creator-ee:v0.4.2

# Patch up entrypoint.sh to fix async job issues with Molecule
# https://github.com/ansible/ansible-runner/issues/1024
# https://github.com/ansible/creator-ee/issues/19
# https://github.com/ansible/ansible-runner/pull/1027/files#diff-4d820c4986f8adb686a55c9ce8318cc2f6658479815a40c4ac7e9af28f7aed95
ADD entrypoint.sh /bin/entrypoint

# Disable role name checking.
# This can be removed when the following is merged and released:
#   https://github.com/ansible-community/molecule/pull/3549
# But the above will require `role_name_check: 2` setting in molecule.yml
RUN sed -i 's/self._install_galaxy_role(self.project_dir, ignore_errors=True)/self._install_galaxy_role(self.project_dir, role_name_check=2, ignore_errors=True)/' /usr/local/lib/python3.8/site-packages/ansible_compat/runtime.py

# Make sure the `ansible` package is installed (rather than just `ansible-base`) so we
# get a good default selection of collections.
RUN pip install 'ansible~=5.8'
```

This then functions almost like the toolset image, although we did have to add `fcqn-builtins` to our `.ansible-lint` configuration, as well.

**Comment by AnonJo** [comment]
Thanks for the informations, but we build a complete own image now.

**Comment by jmazzitelli** [comment]
> Also it seems ansible/toolset is gone, so our complete testing framework isnt working anymore :(

Glad my team isn't the only one complaining about this.

We also just hit this docker problem, too (see [here](https://github.com/kiali/kiali/runs/6806873322?check_suite_focus=true#step:2:543)) Our CI testing is now completely broken - ansible/toolset is gone (so we can't revert back) and the new creator-ee can't use docker, so our GitHubActions CI is completely foo-bared.

**Comment by zhan9san** [comment]
@ssbarnea Do we need to guide users to use podman?

**Comment by vitesse** [comment]
we need some guide that can help us making changes to current molecule, switch away from docker driver, or use podman to run our ansible molecule test in pipeline
