### ISSUE TITLE
ensure we built images using both x64 and aarch64 architecture

### ISSUE THREAD

**Issue by ssbarnea** [ansible/creator-ee#7]
As aarch64 architecture is becoming more popular every day, we should ensure that we built multi-platform images, so everyone can make use of them.

See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md for 
a potential solution to this issue.

- [ ] Ensure https://quay.io/repository/ansible/python-base also includes arm64 architecture
- [ ] Ensure https://quay.io/repository/ansible/ansible-builder also include arm64 architecture
- [ ] Enable ansible-builder to perform multi-platform builds using `docker buildx`
- [ ] Adapt creator-ee pipelines to build and publish both architectures

Depends-On: https://github.com/ansible/ansible-runner/issues/1046
Depends-On: https://github.com/ansible/ansible-builder/issues/373

**Comment by webknjaz** [comment]
I implemented this for pylibssh in the past, happy to do the same here.

**Comment by ziegenberg** [comment]
Would now be a good time to work on this?

**Comment by ssbarnea** [comment]
@mattclay @nitzmahone As I seen the work on new container building at https://github.com/ansible/base-test-container lets have a talk so we can decide what is the easiest path for @ansible/devtools team to build and publish multiple architectures for for creator-ee.

**Comment by ssbarnea** [comment]
@kmf What needs to be done is bit more complex but if you can link to an existing GHA workflow which builds and publishes a dual-arch container, it could clearly help with this task.

**Comment by nitzmahone** [comment]
We're already doing this with all the ansible-test containers using [containmint](https://github.com/ansible/containmint) so the builds are happening on real aarch64 hardware instead of hella slow emulation. It's a little harder to do securely from GHA because the GHA secret stuff is a lot jankier than AZP and there's no Core CI GHA job support, so you need to keep the ansible-core-ci key secret. Take a look at https://github.com/ansible/default-test-container/blob/main/azure-pipelines.yml - it's pretty trivial.

**Comment by kmf** [comment]
@shanemcd mentioned this pull request @ssbarnea 

https://github.com/ansible/receptor/pull/652

**Comment by nitzmahone** [comment]
That's using emulated builds though. It looks like an arch-native release build on `creator-ee` takes ~10min, and IME emulation adds a 5-15x wall-clock penalty. Let's split the difference and call it 10x- that means an emulated build would take 100min to complete. This isn't my project, but if it were, that would be completely unacceptable :laughing:

**Comment by ssbarnea** [comment]
I sorted the performance issue by creating a `creator-base` container which installs all RPMs (including binary wheels). That is the heavy one and we now have a job that updates that base container container weekly.

pip install runs quite fast, even with QEMU virtualization, so no problem here.

Since yesterday with `0.9.3` release, we do have multi-arch containes.
